// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/imgstream/imgstream.proto

package com.proto.imgstream;

public interface CloseStreamResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imgstream.CloseStreamResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string msg = 1;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 1;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
