// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/imgstream/imgstream.proto

package com.proto.imgstream;

public interface CloseStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imgstream.CloseStreamRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
