// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/imgstream/imgstream.proto

package com.proto.imgstream;

public interface ImageRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imgstream.ImageRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 w = 1;</code>
   */
  int getW();

  /**
   * <code>int32 h = 2;</code>
   */
  int getH();

  /**
   * <code>string username = 3;</code>
   */
  java.lang.String getUsername();
  /**
   * <code>string username = 3;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
