// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/imgstream/imgstream.proto

package com.proto.imgstream;

public interface ImageStreamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:imgstream.ImageStream)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 w = 1;</code>
   */
  int getW();

  /**
   * <code>int32 h = 2;</code>
   */
  int getH();

  /**
   * <code>bytes image = 3;</code>
   */
  com.google.protobuf.ByteString getImage();
}
