// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app/src/main/proto/imgstream/imgstream.proto

package com.proto.imgstream;

/**
 * Protobuf type {@code imgstream.ImageStream}
 */
public  final class ImageStream extends
    com.google.protobuf.GeneratedMessageLite<
        ImageStream, ImageStream.Builder> implements
    // @@protoc_insertion_point(message_implements:imgstream.ImageStream)
    ImageStreamOrBuilder {
  private ImageStream() {
    image_ = com.google.protobuf.ByteString.EMPTY;
  }
  public static final int W_FIELD_NUMBER = 1;
  private int w_;
  /**
   * <code>int32 w = 1;</code>
   */
  @java.lang.Override
  public int getW() {
    return w_;
  }
  /**
   * <code>int32 w = 1;</code>
   */
  private void setW(int value) {
    
    w_ = value;
  }
  /**
   * <code>int32 w = 1;</code>
   */
  private void clearW() {
    
    w_ = 0;
  }

  public static final int H_FIELD_NUMBER = 2;
  private int h_;
  /**
   * <code>int32 h = 2;</code>
   */
  @java.lang.Override
  public int getH() {
    return h_;
  }
  /**
   * <code>int32 h = 2;</code>
   */
  private void setH(int value) {
    
    h_ = value;
  }
  /**
   * <code>int32 h = 2;</code>
   */
  private void clearH() {
    
    h_ = 0;
  }

  public static final int IMAGE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString image_;
  /**
   * <code>bytes image = 3;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getImage() {
    return image_;
  }
  /**
   * <code>bytes image = 3;</code>
   */
  private void setImage(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    image_ = value;
  }
  /**
   * <code>bytes image = 3;</code>
   */
  private void clearImage() {
    
    image_ = getDefaultInstance().getImage();
  }

  public static com.proto.imgstream.ImageStream parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.imgstream.ImageStream parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.proto.imgstream.ImageStream parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.imgstream.ImageStream parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.proto.imgstream.ImageStream parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.proto.imgstream.ImageStream parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.proto.imgstream.ImageStream prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code imgstream.ImageStream}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.proto.imgstream.ImageStream, Builder> implements
      // @@protoc_insertion_point(builder_implements:imgstream.ImageStream)
      com.proto.imgstream.ImageStreamOrBuilder {
    // Construct using com.proto.imgstream.ImageStream.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 w = 1;</code>
     */
    @java.lang.Override
    public int getW() {
      return instance.getW();
    }
    /**
     * <code>int32 w = 1;</code>
     */
    public Builder setW(int value) {
      copyOnWrite();
      instance.setW(value);
      return this;
    }
    /**
     * <code>int32 w = 1;</code>
     */
    public Builder clearW() {
      copyOnWrite();
      instance.clearW();
      return this;
    }

    /**
     * <code>int32 h = 2;</code>
     */
    @java.lang.Override
    public int getH() {
      return instance.getH();
    }
    /**
     * <code>int32 h = 2;</code>
     */
    public Builder setH(int value) {
      copyOnWrite();
      instance.setH(value);
      return this;
    }
    /**
     * <code>int32 h = 2;</code>
     */
    public Builder clearH() {
      copyOnWrite();
      instance.clearH();
      return this;
    }

    /**
     * <code>bytes image = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getImage() {
      return instance.getImage();
    }
    /**
     * <code>bytes image = 3;</code>
     */
    public Builder setImage(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setImage(value);
      return this;
    }
    /**
     * <code>bytes image = 3;</code>
     */
    public Builder clearImage() {
      copyOnWrite();
      instance.clearImage();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:imgstream.ImageStream)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.proto.imgstream.ImageStream();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "w_",
            "h_",
            "image_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "\u0003\n";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.proto.imgstream.ImageStream> parser = PARSER;
        if (parser == null) {
          synchronized (com.proto.imgstream.ImageStream.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.proto.imgstream.ImageStream>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:imgstream.ImageStream)
  private static final com.proto.imgstream.ImageStream DEFAULT_INSTANCE;
  static {
    ImageStream defaultInstance = new ImageStream();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ImageStream.class, defaultInstance);
  }

  public static com.proto.imgstream.ImageStream getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ImageStream> PARSER;

  public static com.google.protobuf.Parser<ImageStream> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

