# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: streaming/imgstream/imgstream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='streaming/imgstream/imgstream.proto',
  package='imgstream',
  syntax='proto3',
  serialized_options=_b('Z\013imgstreampb'),
  serialized_pb=_b('\n#streaming/imgstream/imgstream.proto\x12\timgstream\"$\n\x0cImageRequest\x12\t\n\x01w\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\"2\n\x0bImageStream\x12\t\n\x01w\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\x32\x12\n\x10ImgStreamServiceB\rZ\x0bimgstreampbb\x06proto3')
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='imgstream.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='imgstream.ImageRequest.w', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='imgstream.ImageRequest.h', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=86,
)


_IMAGESTREAM = _descriptor.Descriptor(
  name='ImageStream',
  full_name='imgstream.ImageStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='imgstream.ImageStream.w', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='imgstream.ImageStream.h', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='imgstream.ImageStream.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=138,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ImageStream'] = _IMAGESTREAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'streaming.imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageStream = _reflection.GeneratedProtocolMessageType('ImageStream', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESTREAM,
  '__module__' : 'streaming.imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.ImageStream)
  })
_sym_db.RegisterMessage(ImageStream)


DESCRIPTOR._options = None

_IMGSTREAMSERVICE = _descriptor.ServiceDescriptor(
  name='ImgStreamService',
  full_name='imgstream.ImgStreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=140,
  serialized_end=158,
  methods=[
])
_sym_db.RegisterServiceDescriptor(_IMGSTREAMSERVICE)

DESCRIPTOR.services_by_name['ImgStreamService'] = _IMGSTREAMSERVICE

# @@protoc_insertion_point(module_scope)
