# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: imgstream/imgstream.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='imgstream/imgstream.proto',
  package='imgstream',
  syntax='proto3',
  serialized_options=_b('Z\timgstream'),
  serialized_pb=_b('\n\x19imgstream/imgstream.proto\x12\timgstream\"6\n\x0cImageRequest\x12\t\n\x01w\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\"2\n\x0bImageStream\x12\t\n\x01w\x18\x01 \x01(\x05\x12\t\n\x01h\x18\x02 \x01(\x05\x12\r\n\x05image\x18\x03 \x01(\x0c\"&\n\x12\x43loseStreamRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\"\n\x13\x43loseStreamResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xf6\x02\n\x10ImgStreamService\x12\x42\n\x0b\x41skToRasppi\x12\x17.imgstream.ImageRequest\x1a\x16.imgstream.ImageStream\"\x00\x30\x01\x12L\n\x0b\x43loseStream\x12\x1d.imgstream.CloseStreamRequest\x1a\x1e.imgstream.CloseStreamResponse\x12\x46\n\x0eSentFromRasppi\x12\x16.imgstream.ImageStream\x1a\x16.imgstream.ImageStream\"\x00(\x01\x30\x01\x12\x46\n\rAskFromMobile\x12\x17.imgstream.ImageRequest\x1a\x16.imgstream.ImageStream\"\x00(\x01\x30\x01\x12@\n\nSimpleCall\x12\x17.imgstream.ImageRequest\x1a\x17.imgstream.ImageRequest\"\x00\x42\x0bZ\timgstreamb\x06proto3')
)




_IMAGEREQUEST = _descriptor.Descriptor(
  name='ImageRequest',
  full_name='imgstream.ImageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='imgstream.ImageRequest.w', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='imgstream.ImageRequest.h', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='imgstream.ImageRequest.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=94,
)


_IMAGESTREAM = _descriptor.Descriptor(
  name='ImageStream',
  full_name='imgstream.ImageStream',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='imgstream.ImageStream.w', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='h', full_name='imgstream.ImageStream.h', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='imgstream.ImageStream.image', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=146,
)


_CLOSESTREAMREQUEST = _descriptor.Descriptor(
  name='CloseStreamRequest',
  full_name='imgstream.CloseStreamRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='imgstream.CloseStreamRequest.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=186,
)


_CLOSESTREAMRESPONSE = _descriptor.Descriptor(
  name='CloseStreamResponse',
  full_name='imgstream.CloseStreamResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='imgstream.CloseStreamResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=222,
)

DESCRIPTOR.message_types_by_name['ImageRequest'] = _IMAGEREQUEST
DESCRIPTOR.message_types_by_name['ImageStream'] = _IMAGESTREAM
DESCRIPTOR.message_types_by_name['CloseStreamRequest'] = _CLOSESTREAMREQUEST
DESCRIPTOR.message_types_by_name['CloseStreamResponse'] = _CLOSESTREAMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

ImageStream = _reflection.GeneratedProtocolMessageType('ImageStream', (_message.Message,), {
  'DESCRIPTOR' : _IMAGESTREAM,
  '__module__' : 'imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.ImageStream)
  })
_sym_db.RegisterMessage(ImageStream)

CloseStreamRequest = _reflection.GeneratedProtocolMessageType('CloseStreamRequest', (_message.Message,), {
  'DESCRIPTOR' : _CLOSESTREAMREQUEST,
  '__module__' : 'imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.CloseStreamRequest)
  })
_sym_db.RegisterMessage(CloseStreamRequest)

CloseStreamResponse = _reflection.GeneratedProtocolMessageType('CloseStreamResponse', (_message.Message,), {
  'DESCRIPTOR' : _CLOSESTREAMRESPONSE,
  '__module__' : 'imgstream.imgstream_pb2'
  # @@protoc_insertion_point(class_scope:imgstream.CloseStreamResponse)
  })
_sym_db.RegisterMessage(CloseStreamResponse)


DESCRIPTOR._options = None

_IMGSTREAMSERVICE = _descriptor.ServiceDescriptor(
  name='ImgStreamService',
  full_name='imgstream.ImgStreamService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=225,
  serialized_end=599,
  methods=[
  _descriptor.MethodDescriptor(
    name='AskToRasppi',
    full_name='imgstream.ImgStreamService.AskToRasppi',
    index=0,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGESTREAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CloseStream',
    full_name='imgstream.ImgStreamService.CloseStream',
    index=1,
    containing_service=None,
    input_type=_CLOSESTREAMREQUEST,
    output_type=_CLOSESTREAMRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SentFromRasppi',
    full_name='imgstream.ImgStreamService.SentFromRasppi',
    index=2,
    containing_service=None,
    input_type=_IMAGESTREAM,
    output_type=_IMAGESTREAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AskFromMobile',
    full_name='imgstream.ImgStreamService.AskFromMobile',
    index=3,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGESTREAM,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SimpleCall',
    full_name='imgstream.ImgStreamService.SimpleCall',
    index=4,
    containing_service=None,
    input_type=_IMAGEREQUEST,
    output_type=_IMAGEREQUEST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMGSTREAMSERVICE)

DESCRIPTOR.services_by_name['ImgStreamService'] = _IMGSTREAMSERVICE

# @@protoc_insertion_point(module_scope)
